### ISSUE TITLE
Put the init code

### ISSUE THREAD

**Issue by Ethaan** [richsilv/meteor-owl-carousel#2]
Where do you recomend initialize the owlCarousel? i try on the rendered function but just getting plain/text witouth effects

**Comment by Xiangshen-Meng** [comment]
If the slider is only for some of you pages. Maybe initial them in onRendered(or onCreated) is a better.
Something like

```
Template.xxxx.onRendered ->
  this.$(".owl-carousel").owlCarousel()
```

**Comment by paulgnz** [comment]
This works for me...

```
Template.main.onRendered(function(){
    initSlider();
})

initSlider = function() {
    $(document).ready(function() {

        $(".owl-carousel").owlCarousel({

            autoPlay: 3000, //Set AutoPlay to 3 seconds

            items : 1,
            itemsDesktop : [1199,3],
            itemsDesktopSmall : [979,3]

        });

    });
}
```

**Comment by mahiagit** [comment]
Hello guys.

The best way to initialize the owlCarousel in the meteor is from the helper function.

1) In html/template FIle.
Add Template handler like in our case {{initializeCarousel}} in html file. This is to be added where your html snippets ends.

<template name="carousle">

<div>
  <div id="owl-demo" class="owl-carousel">
     {{initializeCarousel}}
  </div>
</div>

</template>

2) In helper File.
Template.carousle.helpers({
    initializeCarousel: function(){
        Deps.autorun(function() {  
            var owl = $('#owl-demo').length;  
            Tracker.afterFlush(function(){  
                $(owl).owlCarousel({
                        autoPlay: 3000, //Set AutoPlay to 3 seconds
                       items : 1,
                       itemsDesktop : [1199,3],
                      itemsDesktopSmall : [979,3]});  
                });
            });
        });
    }
});

This is the way when the required html loads in the DOM and on the calling of the helper handler initiates carousel when required the owl instance.

This snippet works well as per our requirement and listed here with minimal changes for the purpose of example.
If stuck anywhere feel free to ask. 

Thanks,
Mohinder Thakur.

**Comment by zhukovsp** [comment]
@mahiagit Thanks a lot! You saved my day!
