### ISSUE TITLE
The example can't support Collection.find() made.

### ISSUE THREAD

**Issue by carrot93** [richsilv/meteor-owl-carousel#4]
If the data come from db.colleciton. owl-carousel has some repeat-update bugs under meteor.

**Comment by richsilv** [comment]
Try passing [`reactive: false`](http://docs.meteor.com/#/full/find) with your `find`; the package can't prevent the page auto-updating when templates rerender, so you have to pass non-reactive data.

If you need a reactive carousel then you would need to reinitialise it whenever the source data changes; this could be done with `Tracker.autorun`, but it's not something I've tested.
