### ISSUE TITLE
This package cause meteor can not build iOS app

### ISSUE THREAD

**Issue by harlyluyar** [richsilv/meteor-owl-carousel#5]
I follow the instruction, and it works in browser. But when building iOS app, it hangs.
Hope this can be fixed asap.

**Comment by richsilv** [comment]
Any error message?

**Comment by harlyluyar** [comment]
Richard,

No error in the log, only see the app got stuck in the loading page.
After I disabled the code using owl package, it works.

Thanks
GQ


2015-07-15 11:14 GMT-07:00 Richard Silverton <notifications@github.com>:

**Comment by richsilv** [comment]
Unfortunately, I don't develop on a Mac, so there's no way I can reproduce this, even in an emulator.  I'll see if I can get somebody else to take a look, but at present there's not much I can do.

**Comment by harlyluyar** [comment]
I understand. Thanks~~

GQ

2015-07-16 2:13 GMT-07:00 Richard Silverton <notifications@github.com>:
